version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-app}
      POSTGRES_DB: ${POSTGRES_DB:-tmdb}
    ports: ["5432:5432"]
    volumes: ["pgdata:/var/lib/postgresql/data"]

  redis:
    image: redis:7
    ports: ["6379:6379"]

  opensearch:
    image: opensearchproject/opensearch:2
    environment:
      - discovery.type=single-node
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD:-admin}
    ports: ["9200:9200"]

  api:
    build: ./apps/api
    env_file:
      - ./apps/api/.env
    depends_on: [postgres, redis]
    ports: ["8080:80"]

  etl:
    build: ./apps/etl
    env_file:
      - ./apps/etl/.env
    depends_on: [postgres, redis]

  web:
    build: ./apps/web
    env_file:
      - ./apps/web/.env
    depends_on: [api]
    ports: ["3000:3000"]

volumes:
  pgdata: {}
